config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :questions

  root 'home#index'

  get 'current_time' => 'home#current_time'

end

app/models/question.rb
class Question < ActiveRecord::Base

  belongs_to :user

  AUTHOR_FORMAT = /\A.+\z/

  validates :body,
            presence: true,
            length: {minimum: 3}
  validates :author,
            presence: true,
            format: {with: AUTHOR_FORMAT}

  def author_initials
    author.split.map(&:first).join.upcase
  end

  def author
    user.email
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :questions

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

    @current_time = Time.current

  end

  def current_time
    render plain: Time.current
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_action :set_question, only: [:show]
  before_action :set_user_question, only: [:edit, :update, :destroy]

  def index
    @questions = Question.all.page(params[:page]).per(10)
  end

  def new
    @question = current_user.questions.new
  end

  def create
    @question = current_user.questions.new(question_params)

    if @question.save
      redirect_to @question
    else
      render :new
    end

  end

  def update
    if @question.update(question_params)
      redirect_to @question
    else
      render :edit
    end

  end

  def destroy
    @question.destroy!

    redirect_to questions_path
  end

  private

  def question_params
    params.require(:question).permit(:body, :author)
  end

  def set_question
    @question = Question.find(params[:id])
  end

  def set_user_question
    @question = current_user.questions.find(params[:id])
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/home/index.html.erb
<marquee id="currentTime"><%= @current_time %></marquee>

<h1>Welcome to Segfault</h1>
<p>Where Question.joins(:answers)</p>

<p><%= link_to 'Browse Questions', questions_path %></p>

<div style="float: left; background-color: #B00100;" id="test">
  <h1>LOREM IPSUM</h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Segfault</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
<%= current_user.email %>
<%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
<br/>
<% end %>

<%= flash[:notice] %><br />
<%= flash[:alert] %>

<%= yield %>

</body>
</html>

app/views/questions/_form.html.erb
<%= form_for @question do |f| %>

    <% if @question.errors.any? %>
        <div class="alert alert-danger">
          <h2>Please fix <%= pluralize(@question.errors.count, 'error') %>:</h2>
          <ul>
            <% @question.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= f.label :body %><br>
      <%= f.text_field :body %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/questions/_question.html.erb
<tr>
  <td><%= @questions.offset_value + question_counter + 1 %></td>
  <td><%= question.body %></td>
  <td><%= question.author %></td>
  <td><%= link_to 'Show', question_path(question) %></td>
  <% if question.user == current_user %>
  <td><%= link_to 'Edit', edit_question_path(question) %></td>
  <td><%= link_to 'Delete', question_path(question), method: :delete, data: {confirm: 'Are you sure?'} %></td>
  <% end %>
</tr>

app/views/questions/edit.html.erb
<h1>Edit question</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/questions/index.html.erb
<h1>All questions</h1>

<p><%= link_to 'Add Question', new_question_path %></p>

<%= paginate @questions %>

<table>
  <tr>
    <th>Counter</th>
    <th>Body</th>
    <th>Author</th>
    <th colspan="3"></th>
  </tr>

  <%= render @questions %>
</table>

<%= paginate @questions %>

app/views/questions/new.erb
<h1>Create Question</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/questions/show.html.erb
<h1>Question #<%= @question.id %></h1>

<p>
  <strong>Body:</strong>
  <%= @question.body %>
</p>

<p>
  <strong>Author:</strong>
  <%= @question.author %>
</p>
<% if current_user == @question.user %>
<p><%= link_to 'Edit', edit_question_path(@question) %></p>
<p><%= link_to 'Delete', question_path(@question), method: :delete, data: {confirm: "Are you sure?"} %></p>
<% end %>
<p><%= link_to 'Back', :back %></p>